import Head from "next/head";
import Image from "next/image";
import { fetchAPI, getGlobalInfo, getBlogPostsInfo } from "@/lib/api";
import Layout from "@/Components/Layout/Layout";
import BlogPost from "../../Components/Blog/BlogPost/BlogPost";
import Comments from "@/Components/UI/Comments/Comments";
import CommentForm from "@/Components/UI/Comments/CommentForm/CommentForm";
import Pagination from "@/Components/UI/Pagination/Pagination";

import classes from "./index.module.scss";

export async function getStaticProps() {
  const [globalData, pageData, blogPostsData] = await Promise.all([
    getGlobalInfo(),
    fetchAPI(`/sl-home?populate=*`),
    getBlogPostsInfo(),
  ]);
  return {
    props: {
      globalData,
      pageData: pageData.data,
      blogPostsData,
    },
    revalidate: 1,
  };
}

export default function Home({ globalData, pageData, blogPostsData }) {
  // // CONTENTFUL HOME IMAGE ASSET ID (TO GET THE IMAGE INFO LATER)
  // const homeImageID = pageData.items[0].fields.homeImage.sys.id;

  // // CONTENTFUL'S HOME IMAGE
  // const homeImage = pageData.includes.Asset.filter(
  //   (asset) => asset.sys.id === homeImageID
  // );

  return (
    <Layout global={globalData}>
      <Head>
        <title>Seeking Life</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.Home}>
        <div className={classes.Home__Image}>
          <Image
            src={pageData.attributes.TopImage.data.attributes.url}
            fill
            alt={pageData.attributes.TopImage.data.attributes.alternativeText}
            style={{ objectFit: "cover", objectPosition: "center" }}
            priority
            // loader={() => pageData.attributes.TopImage.data.attributes.url}
          />
        </div>

        <section className="row u-margin-medium">
          {blogPostsData.data.map((post) => (
            <BlogPost post={post} key={post.id} />
          ))}
        </section>
        <section className="row u-margin-medium">
          <Pagination pageData={blogPostsData.meta.pagination} />
        </section>
      </main>
    </Layout>
  );
}
