import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Layout from "@/Components/Layout/Layout";

import classes from "./index.module.scss"

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.Home}>
        <div>Hello there</div>
      </main>
    </Layout>
  );
}
