import Head from "next/head";
import Image from "next/image";
import { fetchAPI, getGlobalInfo, getBlogPostsInfo } from "@/lib/api";
import Layout from "@/Components/Layout/Layout";
import Sections from "@/Components/Sections/Sections";
import BlogPost from "../Components/Blog/BlogPost/BlogPost";
import Comments from "@/Components/UI/Comments/Comments";
import CommentForm from "@/Components/UI/Comments/CommentForm/CommentForm";
import Pagination from "@/Components/UI/Pagination/Pagination";
import ContactForm from "@/Components/ContactForm/ContactForm";

import classes from "./index.module.scss";

export async function getStaticProps() {
  const [globalData, pageData, blogPostsData] = await Promise.all([
    getGlobalInfo(),
    fetchAPI(`/sl-home?populate[sections][populate]=*`),
    getBlogPostsInfo(),
  ]);
  return {
    props: {
      globalData,
      pageData: pageData.data,
      blogPostsData,
    },
    revalidate: 1,
  };
}

export default function Home({ globalData, pageData, blogPostsData }) {
  // // CONTENTFUL HOME IMAGE ASSET ID (TO GET THE IMAGE INFO LATER)
  // const homeImageID = pageData.items[0].fields.homeImage.sys.id;

  // // CONTENTFUL'S HOME IMAGE
  // const homeImage = pageData.includes.Asset.filter(
  //   (asset) => asset.sys.id === homeImageID
  // );

  return (
    <Layout global={globalData}>
      <Head>
        <title>Seeking Life</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.Home}>
        {console.log("HERE: ", pageData)}
        {pageData.attributes.sections.map((section, index) => (
          <Sections sectionData={section} key={index} />
        ))}
        <ContactForm globalData={globalData} />
        <div className="row">
          <section className={classes.Home__Hero}>Hero</section>
          <section className={classes.Home__Welcome}>Welcome</section>
          <section className={classes.Home__Testimonial}>Testimonial</section>
          <section className={classes.Home__Photos}>Photos</section>
          <section className={classes.Home__Quote}>Quote</section>
          <section className={classes.Home__CTA}>CTA</section>
          <section className={classes.Home__Contact}>Contact</section>
        </div>
      </main>
    </Layout>
  );
}
